# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        description: Fast iterative OpenShift and Kubernetes development
        logo:
            text: odo
            image:
        nav:
            - item_name: Community
              item_url: '/docs/community'
    footer:
        content:
            logo:
                text: odo
                image:
            copyright: Apache License Version 2.0
        social_list:
            - network_name: github
              profile_url: 'https://github.com/openshift/odo'
    google_analytics:
        tracking_code: UA-119021845-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
